version = 0.1
[default.deploy.parameters]
stack_name = "aihackathon-backend"
resolve_s3 = true
s3_prefix = "aihackathon-backend"
region = "us-west-2"
confirm_changeset = false
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
image_repositories = []
